
// ========================================
// 🔥 TIMER STATE
// Single source of truth for timer runtime
// ========================================

const TimerState = {

    // ========================================
    // CORE TIMER ENGINE
    // ========================================

    timer: null,
    nextTickTime: null,
    isRunning: false,

    // ========================================
    // RUNTIME CLOCK
    // Changes continuously while timer runs
    // ========================================

    timeLeft: 0,
    totalSeconds: 0,
    originalTotalSeconds: 0,
    classStartTime: null,

    // ========================================
    // WORKOUT RUNTIME
    // Current workout position
    // ========================================

    currentPhase: "idle",
    currentSet: 1,
    displaySetNumber: 1,
    rotationCount: 0,
    phaseStartTime: null,
    onBreak: false,

    // ========================================
    // WORKOUT CONFIGURATION
    // Loaded from Google Sheets
    // ========================================

    classBlockLength: null,
    dressOutDuration: null,
    dynamicStretchDuration: null,
    breakDuration: null,
    cooldownDuration: null,

    sheetWorkDuration: null,
    sheetRotateDuration: null,

    manualWorkoutOverride: null,

// ========================================
// WORKOUT DATA
// Generated by WorkoutService
// Used by TimelineService
// ========================================

    workoutData: [],
    phaseSequence: [],
    phaseMeta: [],
    maxSets: 1,

    // TODO:
    // Remove once TimelineService renders directly
    // from phaseMeta.
    timelineData: [],

// ========================================
// AUDIO
// Managed by AudioService
// ========================================
    
    audioCtx: null,
    selectedVoice: null,
    lastCountdownSpoken: null,
    dressWarningSpoken: false,
    phaseJustChanged: false,

    // ========================================
    // AUTO SCHEDULER
    // ========================================

    autoStartTimer: null,
    lastAutoStartMinute: null,
    todayOnlyMode: false,
    forceDateString: null,

    // ========================================
    // COACH SYNC
    // ========================================

    controlAction: null,
    controlTimestamp: null,
    controlPhase: null,
    controlSet: null,
    controlRotation: null,
    lastControlSignature: null,

    // ========================================
    // THEME
    // ========================================

    globalTheme: null

};

window.TimerState = TimerState;
